/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author felsparkle
 */
public class CommunityAdmLogin extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAdmLogin
     */
    public CommunityAdmLogin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CommunityAdmLoginPanel = new javax.swing.JPanel();
        PasswordTxtC = new javax.swing.JPasswordField();
        LoginBtnC = new javax.swing.JButton();
        CloginLbl = new javax.swing.JLabel();
        UsernameLblC = new javax.swing.JLabel();
        PasswordLblC = new javax.swing.JLabel();
        UsernameTxtC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginBtnC.setText("Login");

        CloginLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        CloginLbl.setText("Community Admin's Login");

        UsernameLblC.setText("Username :");

        PasswordLblC.setText("Password :");

        javax.swing.GroupLayout CommunityAdmLoginPanelLayout = new javax.swing.GroupLayout(CommunityAdmLoginPanel);
        CommunityAdmLoginPanel.setLayout(CommunityAdmLoginPanelLayout);
        CommunityAdmLoginPanelLayout.setHorizontalGroup(
            CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityAdmLoginPanelLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addGroup(CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLblC)
                    .addComponent(PasswordLblC))
                .addGap(18, 18, 18)
                .addGroup(CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameTxtC)
                    .addComponent(PasswordTxtC, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommunityAdmLoginPanelLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addGroup(CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CloginLbl)
                    .addGroup(CommunityAdmLoginPanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(LoginBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(393, 393, 393))
        );
        CommunityAdmLoginPanelLayout.setVerticalGroup(
            CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityAdmLoginPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(CloginLbl)
                .addGap(94, 94, 94)
                .addGroup(CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTxtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLblC))
                .addGap(73, 73, 73)
                .addGroup(CommunityAdmLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLblC)
                    .addComponent(PasswordTxtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(LoginBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CommunityAdmLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CommunityAdmLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAdmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloginLbl;
    private javax.swing.JPanel CommunityAdmLoginPanel;
    private javax.swing.JButton LoginBtnC;
    private javax.swing.JLabel PasswordLblC;
    private javax.swing.JPasswordField PasswordTxtC;
    private javax.swing.JLabel UsernameLblC;
    private javax.swing.JTextField UsernameTxtC;
    // End of variables declaration//GEN-END:variables
}
