/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import model.VitalSignsHistory;
import model.VitalSigns;
import model.VitalSignsHistory;

/**
 *
 * @author felsparkle
 */
public class DoctorLogin extends javax.swing.JFrame {

    /**
     * Creates new form DoctorLogin
     */
    
    VitalSignsHistory VitalsHistory;
    
    public DoctorLogin(VitalSignsHistory VitalsHistory) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.VitalsHistory = VitalsHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorLoginPanel = new javax.swing.JPanel();
        DloginLbl = new javax.swing.JLabel();
        UsernameLblD = new javax.swing.JLabel();
        PasswordLblD = new javax.swing.JLabel();
        UsernameTxtD = new javax.swing.JTextField();
        PasswordTxtD = new javax.swing.JPasswordField();
        LoginBtnD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DloginLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        DloginLbl.setText("Doctor's Login");

        UsernameLblD.setText("Username :");

        PasswordLblD.setText("Password :");

        LoginBtnD.setText("Login");
        LoginBtnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorLoginPanelLayout = new javax.swing.GroupLayout(DoctorLoginPanel);
        DoctorLoginPanel.setLayout(DoctorLoginPanelLayout);
        DoctorLoginPanelLayout.setHorizontalGroup(
            DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLoginPanelLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addGroup(DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLblD)
                    .addComponent(PasswordLblD))
                .addGap(18, 18, 18)
                .addGroup(DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameTxtD)
                    .addComponent(PasswordTxtD, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorLoginPanelLayout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addGroup(DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DloginLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorLoginPanelLayout.createSequentialGroup()
                        .addComponent(LoginBtnD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGap(339, 339, 339))
        );
        DoctorLoginPanelLayout.setVerticalGroup(
            DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLoginPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(DloginLbl)
                .addGap(98, 98, 98)
                .addGroup(DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTxtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLblD))
                .addGap(73, 73, 73)
                .addGroup(DoctorLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLblD)
                    .addComponent(PasswordTxtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(LoginBtnD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnDActionPerformed
        // TODO add your handling code here:
        
        DoctorsPOV admin = new DoctorsPOV (VitalsHistory);
        admin.show();
    }//GEN-LAST:event_LoginBtnDActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DloginLbl;
    private javax.swing.JPanel DoctorLoginPanel;
    private javax.swing.JButton LoginBtnD;
    private javax.swing.JLabel PasswordLblD;
    private javax.swing.JPasswordField PasswordTxtD;
    private javax.swing.JLabel UsernameLblD;
    private javax.swing.JTextField UsernameTxtD;
    // End of variables declaration//GEN-END:variables
}
