/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author felsparkle
 */
public class HospitalAdmPOV extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdmPOV
     */
    public HospitalAdmPOV() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HospAdmPOVPnl = new javax.swing.JPanel();
        HospAdmLbl = new javax.swing.JLabel();
        HospAdmPOVScroll = new javax.swing.JScrollPane();
        HospAdmPOVTbl = new javax.swing.JTable();
        HospAdmSearchLbl = new javax.swing.JLabel();
        HospAdmSearchTxt = new javax.swing.JTextField();
        HospNameLbl = new javax.swing.JLabel();
        HospNameTxt = new javax.swing.JTextField();
        DoctorNameLbl = new javax.swing.JLabel();
        DocNameTxt = new javax.swing.JTextField();
        CityLbl = new javax.swing.JLabel();
        CityTxt = new javax.swing.JTextField();
        HospAdmAddBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HospAdmLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        HospAdmLbl.setText("Hospital Admin");

        HospAdmPOVTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hospital Name", "Doctor's Name", "City"
            }
        ));
        HospAdmPOVScroll.setViewportView(HospAdmPOVTbl);

        HospAdmSearchLbl.setText("Search:");

        HospNameLbl.setText("Hospital Name:");

        HospNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospNameTxtActionPerformed(evt);
            }
        });

        DoctorNameLbl.setText("Doctor's Name");

        DocNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocNameTxtActionPerformed(evt);
            }
        });

        CityLbl.setText("City:");

        CityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTxtActionPerformed(evt);
            }
        });

        HospAdmAddBtn.setText("Add");
        HospAdmAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospAdmAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HospAdmPOVPnlLayout = new javax.swing.GroupLayout(HospAdmPOVPnl);
        HospAdmPOVPnl.setLayout(HospAdmPOVPnlLayout);
        HospAdmPOVPnlLayout.setHorizontalGroup(
            HospAdmPOVPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospAdmPOVPnlLayout.createSequentialGroup()
                .addGroup(HospAdmPOVPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HospAdmPOVPnlLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(HospAdmPOVScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HospAdmPOVPnlLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(HospAdmSearchLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HospAdmSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospAdmPOVPnlLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(HospAdmPOVPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospAdmPOVPnlLayout.createSequentialGroup()
                        .addComponent(HospAdmLbl)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospAdmPOVPnlLayout.createSequentialGroup()
                        .addComponent(HospNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HospNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(DoctorNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DocNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(CityLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospAdmPOVPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HospAdmAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(430, 430, 430))
        );
        HospAdmPOVPnlLayout.setVerticalGroup(
            HospAdmPOVPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospAdmPOVPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HospAdmLbl)
                .addGap(18, 18, 18)
                .addComponent(HospAdmPOVScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HospAdmPOVPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospAdmSearchLbl)
                    .addComponent(HospAdmSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(HospAdmPOVPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospNameLbl)
                    .addComponent(HospNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorNameLbl)
                    .addComponent(DocNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityLbl)
                    .addComponent(CityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(HospAdmAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HospAdmPOVPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HospAdmPOVPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HospNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospNameTxtActionPerformed

    private void DocNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocNameTxtActionPerformed

    private void CityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTxtActionPerformed

    private void HospAdmAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospAdmAddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospAdmAddBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalAdmPOV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityLbl;
    private javax.swing.JTextField CityTxt;
    private javax.swing.JTextField DocNameTxt;
    private javax.swing.JLabel DoctorNameLbl;
    private javax.swing.JButton HospAdmAddBtn;
    private javax.swing.JLabel HospAdmLbl;
    private javax.swing.JPanel HospAdmPOVPnl;
    private javax.swing.JScrollPane HospAdmPOVScroll;
    private javax.swing.JTable HospAdmPOVTbl;
    private javax.swing.JLabel HospAdmSearchLbl;
    private javax.swing.JTextField HospAdmSearchTxt;
    private javax.swing.JLabel HospNameLbl;
    private javax.swing.JTextField HospNameTxt;
    // End of variables declaration//GEN-END:variables
}
