/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author felsparkle
 */
public class PatientsPOV extends javax.swing.JFrame {

    /**
     * Creates new form PatientsPOV
     */
    public PatientsPOV() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientsPOV = new javax.swing.JSplitPane();
        PaBookAptPnl = new javax.swing.JPanel();
        PaBookAptLbl = new javax.swing.JLabel();
        PaAptScroll = new javax.swing.JScrollPane();
        PaAptTbl = new javax.swing.JTable();
        PaAptComboBox = new javax.swing.JComboBox<>();
        PaBookAptBtn = new javax.swing.JButton();
        PaSearchDocLbl = new javax.swing.JLabel();
        PaSearchDocTxt = new javax.swing.JTextField();
        PaVitalSignsPnl = new javax.swing.JPanel();
        PaBookAptLbl1 = new javax.swing.JLabel();
        PaVitalSignsScroll = new javax.swing.JScrollPane();
        PaVitalSignsTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaBookAptPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PaBookAptLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        PaBookAptLbl.setText("Book an Appointment");

        PaAptTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doc Name", "Hosp Name", "City", "Pin"
            }
        ));
        PaAptScroll.setViewportView(PaAptTbl);

        PaAptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PaAptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaAptComboBoxActionPerformed(evt);
            }
        });

        PaBookAptBtn.setText("Book Appointment");

        PaSearchDocLbl.setText("Search Doctor:");

        javax.swing.GroupLayout PaBookAptPnlLayout = new javax.swing.GroupLayout(PaBookAptPnl);
        PaBookAptPnl.setLayout(PaBookAptPnlLayout);
        PaBookAptPnlLayout.setHorizontalGroup(
            PaBookAptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaBookAptPnlLayout.createSequentialGroup()
                .addGroup(PaBookAptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaBookAptPnlLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(PaBookAptLbl))
                    .addGroup(PaBookAptPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PaAptScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaBookAptPnlLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(PaBookAptBtn)
                        .addGap(28, 28, 28)
                        .addComponent(PaAptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaBookAptPnlLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(PaSearchDocLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaSearchDocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PaBookAptPnlLayout.setVerticalGroup(
            PaBookAptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaBookAptPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaBookAptLbl)
                .addGap(18, 18, 18)
                .addComponent(PaAptScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PaBookAptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaSearchDocLbl)
                    .addComponent(PaSearchDocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(PaBookAptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaBookAptBtn)
                    .addComponent(PaAptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        PatientsPOV.setLeftComponent(PaBookAptPnl);

        PaVitalSignsPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PaBookAptLbl1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        PaBookAptLbl1.setText("Your Vital Signs");

        PaVitalSignsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Weight", "Height", "Temperature", "Pressure", "Pulse"
            }
        ));
        PaVitalSignsScroll.setViewportView(PaVitalSignsTbl);

        javax.swing.GroupLayout PaVitalSignsPnlLayout = new javax.swing.GroupLayout(PaVitalSignsPnl);
        PaVitalSignsPnl.setLayout(PaVitalSignsPnlLayout);
        PaVitalSignsPnlLayout.setHorizontalGroup(
            PaVitalSignsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaVitalSignsPnlLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(PaVitalSignsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaVitalSignsPnlLayout.createSequentialGroup()
                        .addComponent(PaBookAptLbl1)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaVitalSignsPnlLayout.createSequentialGroup()
                        .addComponent(PaVitalSignsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        PaVitalSignsPnlLayout.setVerticalGroup(
            PaVitalSignsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaVitalSignsPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaBookAptLbl1)
                .addGap(18, 18, 18)
                .addComponent(PaVitalSignsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        PatientsPOV.setRightComponent(PaVitalSignsPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientsPOV)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientsPOV)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaAptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaAptComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaAptComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsPOV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsPOV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PaAptComboBox;
    private javax.swing.JScrollPane PaAptScroll;
    private javax.swing.JTable PaAptTbl;
    private javax.swing.JButton PaBookAptBtn;
    private javax.swing.JLabel PaBookAptLbl;
    private javax.swing.JLabel PaBookAptLbl1;
    private javax.swing.JPanel PaBookAptPnl;
    private javax.swing.JLabel PaSearchDocLbl;
    private javax.swing.JTextField PaSearchDocTxt;
    private javax.swing.JPanel PaVitalSignsPnl;
    private javax.swing.JScrollPane PaVitalSignsScroll;
    private javax.swing.JTable PaVitalSignsTbl;
    private javax.swing.JSplitPane PatientsPOV;
    // End of variables declaration//GEN-END:variables
}
