/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author felsparkle
 */
public class SystemAdmPOVhospital extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdmPOVhospital
     */
    public SystemAdmPOVhospital() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SystemAdminPOVSplitHosp = new javax.swing.JSplitPane();
        SaHspPnl = new javax.swing.JPanel();
        SaHspLbl = new javax.swing.JLabel();
        SaHspNameLbl1 = new javax.swing.JLabel();
        SaHspNameTxt1 = new javax.swing.JTextField();
        SaHspPinLbl1 = new javax.swing.JLabel();
        SaHspPinTxt1 = new javax.swing.JTextField();
        SaHspCityLbl1 = new javax.swing.JLabel();
        SaHspCityTxt1 = new javax.swing.JTextField();
        SaHspAddBtn = new javax.swing.JButton();
        SaHspTbl = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SaSearchHspLbl = new javax.swing.JLabel();
        SaSearchHspTxt = new javax.swing.JTextField();
        SaHspNameLbl2 = new javax.swing.JLabel();
        SaHspNameTxt2 = new javax.swing.JTextField();
        SaHspPinLbl2 = new javax.swing.JLabel();
        SaHspPinTxt2 = new javax.swing.JTextField();
        SaHspCityLbl2 = new javax.swing.JLabel();
        SaHspCityTxt2 = new javax.swing.JTextField();
        SaHspUpdateBtn = new javax.swing.JButton();
        SaHspDeleteBtn = new javax.swing.JButton();
        SaDocPnl = new javax.swing.JPanel();
        SaDocLbl = new javax.swing.JLabel();
        SaDocNameLbl1 = new javax.swing.JLabel();
        SaDocNameTxt1 = new javax.swing.JTextField();
        SaDocHospNameLbl1 = new javax.swing.JLabel();
        SaDocHospNameTxt1 = new javax.swing.JTextField();
        SaDocCityLbl1 = new javax.swing.JLabel();
        SaDocCityTxt1 = new javax.swing.JTextField();
        SaDocAddBtn = new javax.swing.JButton();
        SaDocTbl = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SaSearchDocLbl = new javax.swing.JLabel();
        SaSearchDocTxt = new javax.swing.JTextField();
        SaDocNameLbl2 = new javax.swing.JLabel();
        SaDocNameTxt2 = new javax.swing.JTextField();
        SaDocHospNameLbl2 = new javax.swing.JLabel();
        SaDocHospNameTxt2 = new javax.swing.JTextField();
        SaDocCityLbl2 = new javax.swing.JLabel();
        SaDocCityTxt2 = new javax.swing.JTextField();
        SaDocUpdateBtn = new javax.swing.JButton();
        SaDocDeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaHspPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SaHspLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        SaHspLbl.setText("Hospital");

        SaHspNameLbl1.setText("Name of the Hospital:");

        SaHspPinLbl1.setText("Pin Code:");

        SaHspPinTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspPinTxt1ActionPerformed(evt);
            }
        });

        SaHspCityLbl1.setText("City:");

        SaHspCityTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspCityTxt1ActionPerformed(evt);
            }
        });

        SaHspAddBtn.setText("Add");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name of Hosp", "Pin Code", "City"
            }
        ));
        SaHspTbl.setViewportView(jTable1);

        SaSearchHspLbl.setText("Search Hospital:");

        SaHspNameLbl2.setText("Name of the Hospital:");

        SaHspPinLbl2.setText("Pin Code:");

        SaHspPinTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspPinTxt2ActionPerformed(evt);
            }
        });

        SaHspCityLbl2.setText("City:");

        SaHspCityTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspCityTxt2ActionPerformed(evt);
            }
        });

        SaHspUpdateBtn.setText("Update");

        SaHspDeleteBtn.setText("Delete");

        javax.swing.GroupLayout SaHspPnlLayout = new javax.swing.GroupLayout(SaHspPnl);
        SaHspPnl.setLayout(SaHspPnlLayout);
        SaHspPnlLayout.setHorizontalGroup(
            SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaHspPnlLayout.createSequentialGroup()
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(SaHspLbl))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaHspPinLbl1)
                            .addComponent(SaHspNameLbl1)
                            .addComponent(SaHspCityLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SaHspPnlLayout.createSequentialGroup()
                                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SaHspPinTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SaHspCityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(SaHspAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SaHspNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(SaSearchHspLbl)
                        .addGap(18, 18, 18)
                        .addComponent(SaSearchHspTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaHspNameLbl2)
                            .addComponent(SaHspPinLbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaHspCityLbl2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaHspNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaHspPinTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaHspCityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(SaHspUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(SaHspDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SaHspTbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SaHspPnlLayout.setVerticalGroup(
            SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaHspPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaHspLbl)
                .addGap(19, 19, 19)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaHspNameLbl1)
                    .addComponent(SaHspNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaHspAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SaHspPnlLayout.createSequentialGroup()
                                .addComponent(SaHspPinLbl1)
                                .addGap(29, 29, 29)
                                .addComponent(SaHspCityLbl1))))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SaHspPinTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SaHspCityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(SaHspTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaSearchHspLbl)
                    .addComponent(SaSearchHspTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaHspNameLbl2)
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addComponent(SaHspNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaHspPinTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaHspPinLbl2))
                        .addGap(18, 18, 18)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaHspCityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaHspCityLbl2))))
                .addGap(31, 31, 31)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaHspUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaHspDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        SystemAdminPOVSplitHosp.setLeftComponent(SaHspPnl);

        SaDocPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SaDocLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        SaDocLbl.setText("Doctor");

        SaDocNameLbl1.setText("Name of the Doctor:");

        SaDocHospNameLbl1.setText("Hospital Name:");

        SaDocHospNameTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocHospNameTxt1ActionPerformed(evt);
            }
        });

        SaDocCityLbl1.setText("City:");

        SaDocCityTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocCityTxt1ActionPerformed(evt);
            }
        });

        SaDocAddBtn.setText("Add");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name od Doc", "Hospital Name", "City"
            }
        ));
        SaDocTbl.setViewportView(jTable2);

        SaSearchDocLbl.setText("Search Doctor:");

        SaDocNameLbl2.setText("Name of the Doctor:");

        SaDocHospNameLbl2.setText("Hospital Name:");

        SaDocHospNameTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocHospNameTxt2ActionPerformed(evt);
            }
        });

        SaDocCityLbl2.setText("City:");

        SaDocCityTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocCityTxt2ActionPerformed(evt);
            }
        });

        SaDocUpdateBtn.setText("Update");

        SaDocDeleteBtn.setText("Delete");

        javax.swing.GroupLayout SaDocPnlLayout = new javax.swing.GroupLayout(SaDocPnl);
        SaDocPnl.setLayout(SaDocPnlLayout);
        SaDocPnlLayout.setHorizontalGroup(
            SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaDocPnlLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(SaDocLbl)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SaDocPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaDocHospNameLbl1)
                                .addComponent(SaDocNameLbl1)
                                .addComponent(SaDocCityLbl1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaDocCityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaDocHospNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaDocNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaDocAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaDocPnlLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(SaDocTbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SaDocPnlLayout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(SaSearchDocLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(SaSearchDocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SaDocPnlLayout.createSequentialGroup()
                                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SaDocNameLbl2)
                                        .addComponent(SaDocHospNameLbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SaDocCityLbl2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(21, 21, 21)
                                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SaDocNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SaDocHospNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SaDocCityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(SaDocPnlLayout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addComponent(SaDocUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(SaDocDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        SaDocPnlLayout.setVerticalGroup(
            SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaDocPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaDocLbl)
                .addContainerGap(616, Short.MAX_VALUE))
            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SaDocPnlLayout.createSequentialGroup()
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaDocNameLbl1)
                                .addComponent(SaDocNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaDocHospNameLbl1)
                                .addComponent(SaDocHospNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaDocCityLbl1)
                                .addComponent(SaDocCityTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(SaDocAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(SaDocTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaSearchDocLbl)
                        .addComponent(SaSearchDocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SaDocNameLbl2)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addComponent(SaDocNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaDocHospNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaDocHospNameLbl2))
                            .addGap(18, 18, 18)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaDocCityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaDocCityLbl2))))
                    .addGap(31, 31, 31)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaDocUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaDocDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)))
        );

        SystemAdminPOVSplitHosp.setRightComponent(SaDocPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminPOVSplitHosp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminPOVSplitHosp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaHspPinTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspPinTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaHspPinTxt1ActionPerformed

    private void SaHspCityTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspCityTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaHspCityTxt1ActionPerformed

    private void SaHspPinTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspPinTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaHspPinTxt2ActionPerformed

    private void SaHspCityTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspCityTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaHspCityTxt2ActionPerformed

    private void SaDocHospNameTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocHospNameTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaDocHospNameTxt1ActionPerformed

    private void SaDocCityTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocCityTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaDocCityTxt1ActionPerformed

    private void SaDocHospNameTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocHospNameTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaDocHospNameTxt2ActionPerformed

    private void SaDocCityTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocCityTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaDocCityTxt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdmPOVhospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdmPOVhospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdmPOVhospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdmPOVhospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdmPOVhospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaDocAddBtn;
    private javax.swing.JLabel SaDocCityLbl1;
    private javax.swing.JLabel SaDocCityLbl2;
    private javax.swing.JTextField SaDocCityTxt1;
    private javax.swing.JTextField SaDocCityTxt2;
    private javax.swing.JButton SaDocDeleteBtn;
    private javax.swing.JLabel SaDocHospNameLbl1;
    private javax.swing.JLabel SaDocHospNameLbl2;
    private javax.swing.JTextField SaDocHospNameTxt1;
    private javax.swing.JTextField SaDocHospNameTxt2;
    private javax.swing.JLabel SaDocLbl;
    private javax.swing.JLabel SaDocNameLbl1;
    private javax.swing.JLabel SaDocNameLbl2;
    private javax.swing.JTextField SaDocNameTxt1;
    private javax.swing.JTextField SaDocNameTxt2;
    private javax.swing.JPanel SaDocPnl;
    private javax.swing.JScrollPane SaDocTbl;
    private javax.swing.JButton SaDocUpdateBtn;
    private javax.swing.JButton SaHspAddBtn;
    private javax.swing.JLabel SaHspCityLbl1;
    private javax.swing.JLabel SaHspCityLbl2;
    private javax.swing.JTextField SaHspCityTxt1;
    private javax.swing.JTextField SaHspCityTxt2;
    private javax.swing.JButton SaHspDeleteBtn;
    private javax.swing.JLabel SaHspLbl;
    private javax.swing.JLabel SaHspNameLbl1;
    private javax.swing.JLabel SaHspNameLbl2;
    private javax.swing.JTextField SaHspNameTxt1;
    private javax.swing.JTextField SaHspNameTxt2;
    private javax.swing.JLabel SaHspPinLbl1;
    private javax.swing.JLabel SaHspPinLbl2;
    private javax.swing.JTextField SaHspPinTxt1;
    private javax.swing.JTextField SaHspPinTxt2;
    private javax.swing.JPanel SaHspPnl;
    private javax.swing.JScrollPane SaHspTbl;
    private javax.swing.JButton SaHspUpdateBtn;
    private javax.swing.JLabel SaSearchDocLbl;
    private javax.swing.JTextField SaSearchDocTxt;
    private javax.swing.JLabel SaSearchHspLbl;
    private javax.swing.JTextField SaSearchHspTxt;
    private javax.swing.JSplitPane SystemAdminPOVSplitHosp;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
