/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Community;
import model.CommunityHistory;
import model.HospitalHistory;
import model.Hospital;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.DoctorHistory;
import model.DoctorNew;
import model.DoctorNewHistory;
import model.Person;
import model.PersonHistory;

/**
 *
 * @author felsparkle
 */
public class SystemAdmPOVhospital extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdmPOVhospital
     * 
     */
    private String[] PinCodeArray;
    HospitalHistory HospHistory;
    CommunityHistory CommHistory;
    private String[] CityArray;
    private String[] HospArray;
    private String [] CityArray1;
    DoctorHistory DocHistory;
    DoctorNewHistory DocNewHistory;
    PersonHistory History;
    private String[] DocArray;
    
    public SystemAdmPOVhospital(CommunityHistory CommHistory,HospitalHistory HospHistory,DoctorHistory DocHistory,DoctorNewHistory DocNewHistory,PersonHistory History) {
        
    
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        
        this.HospHistory = HospHistory;
        this.DocHistory = DocHistory;
        this.CommHistory = CommHistory;
        this.History = History;
        this.DocNewHistory = DocNewHistory;
        
        
        
        int PinCodeArraySize = CommHistory.getCommHistory().size();
        this.PinCodeArray = new String[PinCodeArraySize];
        int itr = 0;
        
        for(Community community:CommHistory.getCommHistory()){
            this.PinCodeArray [itr++] = community.getPinCode();
        }
        
        HospitalPinCombo.setModel(new javax.swing.DefaultComboBoxModel<>(this.PinCodeArray));
        
        



        
        /////////////////////
    
        int CityArraySize = CommHistory.getCommHistory().size();
        this.CityArray = new String[CityArraySize];
        int itr1 = 0;
       
        for (Community community:CommHistory.getCommHistory() ){
            this.CityArray [itr1++] = community.getCity();
        }
       
        HospitalCityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(this.CityArray));
        
        
        /////////////////////
        
        /*int DocArraySize = DocHistory.getDocHistory().size();
        this.DocArray = new String[DocArraySize];
        int itr4 = 0;
        
        for(Doctor doctor:DocHistory.getDocHistory()){
            this.DocArray [itr4++] = doctor.getName();
        }
        DocNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(this.DocArray));*/
        
        
        
       
       
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SystemAdminPOVSplitHosp = new javax.swing.JSplitPane();
        SaHspPnl = new javax.swing.JPanel();
        SaHspLbl = new javax.swing.JLabel();
        SaHspNameLbl1 = new javax.swing.JLabel();
        SaHspNameTxt1 = new javax.swing.JTextField();
        SaHspPinLbl1 = new javax.swing.JLabel();
        SaHspCityLbl1 = new javax.swing.JLabel();
        SaHspAddBtn = new javax.swing.JButton();
        SaHspTbl = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SaSearchHspLbl = new javax.swing.JLabel();
        SaSearchHspTxt = new javax.swing.JTextField();
        SaHspNameLbl2 = new javax.swing.JLabel();
        SaHspNameTxt2 = new javax.swing.JTextField();
        SaHspUpdateBtn = new javax.swing.JButton();
        SaHspDeleteBtn = new javax.swing.JButton();
        HospitalPinCombo = new javax.swing.JComboBox<>();
        HospitalCityCombo = new javax.swing.JComboBox<>();
        SaDocPnl = new javax.swing.JPanel();
        SaDocLbl = new javax.swing.JLabel();
        SaDocNameLbl1 = new javax.swing.JLabel();
        SaDocHospNameLbl1 = new javax.swing.JLabel();
        SaDocCityLbl1 = new javax.swing.JLabel();
        SaDocAddBtn = new javax.swing.JButton();
        SaDocTbl = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SaSearchDocLbl = new javax.swing.JLabel();
        SaSearchDocTxt = new javax.swing.JTextField();
        SaDocNameLbl2 = new javax.swing.JLabel();
        SaDocNameTxt2 = new javax.swing.JTextField();
        SaDocHospNameLbl2 = new javax.swing.JLabel();
        SaDocHospNameTxt2 = new javax.swing.JTextField();
        SaDocCityLbl2 = new javax.swing.JLabel();
        SaDocCityTxt2 = new javax.swing.JTextField();
        SaDocUpdateBtn = new javax.swing.JButton();
        SaDocDeleteBtn = new javax.swing.JButton();
        DoctorCityCombo = new javax.swing.JComboBox<>();
        HospNameCombo = new javax.swing.JComboBox<>();
        DocNameTxt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaHspPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SaHspLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        SaHspLbl.setText("Hospital");

        SaHspNameLbl1.setText("Name of the Hospital:");

        SaHspPinLbl1.setText("Pin Code:");

        SaHspCityLbl1.setText("City:");

        SaHspAddBtn.setText("Add");
        SaHspAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspAddBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name of Hosp", "Pin Code", "City"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        SaHspTbl.setViewportView(jTable1);

        SaSearchHspLbl.setText("Search Hospital:");

        SaHspNameLbl2.setText("Name of the Hospital:");

        SaHspUpdateBtn.setText("Update");
        SaHspUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspUpdateBtnActionPerformed(evt);
            }
        });

        SaHspDeleteBtn.setText("Delete");
        SaHspDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaHspDeleteBtnActionPerformed(evt);
            }
        });

        HospitalPinCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        HospitalCityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        HospitalCityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalCityComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaHspPnlLayout = new javax.swing.GroupLayout(SaHspPnl);
        SaHspPnl.setLayout(SaHspPnlLayout);
        SaHspPnlLayout.setHorizontalGroup(
            SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaHspPnlLayout.createSequentialGroup()
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(SaHspLbl))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaHspPinLbl1)
                            .addComponent(SaHspNameLbl1)
                            .addComponent(SaHspCityLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SaHspPnlLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(HospitalPinCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospitalCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addComponent(SaHspAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SaHspNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(SaSearchHspLbl)
                        .addGap(18, 18, 18)
                        .addComponent(SaSearchHspTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SaHspNameLbl2)
                        .addGap(21, 21, 21)
                        .addComponent(SaHspNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(SaHspUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(SaHspDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SaHspPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SaHspTbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SaHspPnlLayout.setVerticalGroup(
            SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaHspPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaHspLbl)
                .addGap(19, 19, 19)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaHspNameLbl1)
                    .addComponent(SaHspNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SaHspAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SaHspPnlLayout.createSequentialGroup()
                            .addComponent(SaHspPinLbl1)
                            .addGap(26, 26, 26)
                            .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaHspCityLbl1)
                                .addComponent(HospitalCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(HospitalPinCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(SaHspTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaSearchHspLbl)
                    .addComponent(SaSearchHspTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaHspNameLbl2)
                    .addComponent(SaHspNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(SaHspPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaHspUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaHspDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        SystemAdminPOVSplitHosp.setLeftComponent(SaHspPnl);

        SaDocPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SaDocLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        SaDocLbl.setText("Doctor");

        SaDocNameLbl1.setText("Name of the Doctor:");

        SaDocHospNameLbl1.setText("Hospital Name:");

        SaDocCityLbl1.setText("City:");

        SaDocAddBtn.setText("Add");
        SaDocAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocAddBtnActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name od Doc", "Hospital Name", "City"
            }
        ));
        SaDocTbl.setViewportView(jTable2);

        SaSearchDocLbl.setText("Search Doctor:");

        SaDocNameLbl2.setText("Name of the Doctor:");

        SaDocHospNameLbl2.setText("Hospital Name:");

        SaDocHospNameTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocHospNameTxt2ActionPerformed(evt);
            }
        });

        SaDocCityLbl2.setText("City:");

        SaDocCityTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocCityTxt2ActionPerformed(evt);
            }
        });

        SaDocUpdateBtn.setText("Update");

        SaDocDeleteBtn.setText("Delete");
        SaDocDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaDocDeleteBtnActionPerformed(evt);
            }
        });

        DoctorCityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        HospNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout SaDocPnlLayout = new javax.swing.GroupLayout(SaDocPnl);
        SaDocPnl.setLayout(SaDocPnlLayout);
        SaDocPnlLayout.setHorizontalGroup(
            SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaDocPnlLayout.createSequentialGroup()
                .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DocNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(SaDocLbl))
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SaDocPnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaDocHospNameLbl1)
                                .addComponent(SaDocNameLbl1)
                                .addComponent(SaDocCityLbl1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                            .addComponent(SaDocAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaDocPnlLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(SaDocTbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SaDocPnlLayout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(SaSearchDocLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(SaSearchDocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SaDocPnlLayout.createSequentialGroup()
                                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SaDocNameLbl2)
                                        .addComponent(SaDocHospNameLbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SaDocCityLbl2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(21, 21, 21)
                                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SaDocNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SaDocHospNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SaDocCityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(SaDocPnlLayout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addComponent(SaDocUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(SaDocDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        SaDocPnlLayout.setVerticalGroup(
            SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaDocPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaDocLbl)
                .addGap(21, 21, 21)
                .addComponent(DocNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HospNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SaDocPnlLayout.createSequentialGroup()
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(SaDocNameLbl1)
                            .addGap(18, 18, 18)
                            .addComponent(SaDocHospNameLbl1)
                            .addGap(18, 18, 18)
                            .addComponent(SaDocCityLbl1))
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(SaDocAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(24, 24, 24)
                    .addComponent(SaDocTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaSearchDocLbl)
                        .addComponent(SaSearchDocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SaDocNameLbl2)
                        .addGroup(SaDocPnlLayout.createSequentialGroup()
                            .addComponent(SaDocNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaDocHospNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaDocHospNameLbl2))
                            .addGap(18, 18, 18)
                            .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaDocCityTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaDocCityLbl2))))
                    .addGap(31, 31, 31)
                    .addGroup(SaDocPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaDocUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaDocDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)))
        );

        SystemAdminPOVSplitHosp.setRightComponent(SaDocPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminPOVSplitHosp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminPOVSplitHosp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaDocHospNameTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocHospNameTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaDocHospNameTxt2ActionPerformed

    private void SaDocCityTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocCityTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaDocCityTxt2ActionPerformed

    private void SaHspAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspAddBtnActionPerformed
        // TODO add your handling code here:
        try{
            String HospitalName = SaHspNameTxt1.getText();
            String PinCode = HospitalPinCombo.getSelectedItem().toString();
            String City = HospitalCityCombo.getSelectedItem().toString();
            
//            Hospital h = this.HospHistory.addNewHospital();
//            
//            h.setHospitalName(HospitalName);
//            h.setCity(City);
//            h.setPinCode(PinCode);
        Hospital h = new Hospital(HospitalName, PinCode, City);
//        Hospital h = this.HospHistory.addNewHospital();
        HospitalHistory.addNewHospital(h);
      
            
            JOptionPane.showMessageDialog(this, "Details added.");
            populateTable();
            
            SaHspNameTxt1.setText("");
            
            
            //combo box code for Hospital Name
            int HospArraySize = HospHistory.getHospHistory().size();
        this.HospArray = new String[HospArraySize];
        int itr2 = 0;
        
        for (Hospital hospital: HospHistory.getHospHistory()){
            this.HospArray [itr2++] = hospital.getHospitalName();
                    
        }
        HospNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(this.HospArray));
        
        
        //combo box code for City
        int CityArraySize = HospHistory.getHospHistory().size();
        this.CityArray1 = new String[CityArraySize];
        int itr3 = 0;
       
        for (Hospital hospital:HospHistory.getHospHistory() ){
            this.CityArray1 [itr3++] = hospital.getCity();
        }
       
        DoctorCityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(this.CityArray1));
        
        
        
        
            
            
            
            
        }
        catch (Exception e){
            //System.out.println(e);
            //JOptionPane.showMessageDialog(this, "Please make sure all data is entered");
            
        }
    }//GEN-LAST:event_SaHspAddBtnActionPerformed

    private void SaHspDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspDeleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();
         if (selectedRowIndex<0){
             
             JOptionPane.showMessageDialog(this,"Select a row to delete.");
             return;
         
         }
         
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         Hospital selectedHospital = (Hospital) model.getValueAt(selectedRowIndex, 0); 
         
         HospHistory.deleteHospital(selectedHospital);
             
             JOptionPane.showMessageDialog(this,"Hospital deleted.");
             populateTable();
    }//GEN-LAST:event_SaHspDeleteBtnActionPerformed

    private void SaHspUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaHspUpdateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
      if(jTable1.getSelectedRowCount()==1){
         
     
        String HospitalName = SaHspNameTxt2.getText();
        
        
        
        
        
       
        model.setValueAt(HospitalName,jTable1.getSelectedRow(),0);
        
        
        
        for(Hospital h : HospHistory.getHospHistory()){
          
            
                h.setHospitalName(HospitalName);
                
                
                
                
            
            
        }
        
       
       
        JOptionPane.showMessageDialog(this,"Community Details Updated Successfully.");
        
      }
    }//GEN-LAST:event_SaHspUpdateBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();


            String HospitalName = model.getValueAt(jTable1.getSelectedRow(),0).toString();
            
            
            

            SaHspNameTxt2.setText(HospitalName);
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void HospitalCityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalCityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalCityComboActionPerformed

    private void SaDocAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocAddBtnActionPerformed
        // TODO add your handling code here:
        
            String DoctorName = DocNameTxt1.getText();
            String HospitalName = HospNameCombo.getSelectedItem().toString();
            String City = DoctorCityCombo.getSelectedItem().toString();
            
            DoctorNew d = this.DocNewHistory.addNewDoctor();
            
            d.setDoctorName(DoctorName);
            d.setHospitalName(HospitalName);
            d.setCity(City);
            
            
            JOptionPane.showMessageDialog(this, "Details added.");
            populateTableNew();
            
            
            
        
        
            
        
        
          
            
    }//GEN-LAST:event_SaDocAddBtnActionPerformed

    private void SaDocDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaDocDeleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable2.getSelectedRow();
         if (selectedRowIndex<0){
             
             JOptionPane.showMessageDialog(this,"Select a row to delete.");
             return;
         
         }
         
         DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
         DoctorNew selectedDoctor = (DoctorNew) model.getValueAt(selectedRowIndex, 0); 
         
         DocNewHistory.deleteDoctorNew(selectedDoctor);
             
             JOptionPane.showMessageDialog(this,"It's Illegal to delete Doctor.");
             populateTable();
        
        
    }//GEN-LAST:event_SaDocDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DocNameTxt1;
    private javax.swing.JComboBox<String> DoctorCityCombo;
    private javax.swing.JComboBox<String> HospNameCombo;
    private javax.swing.JComboBox<String> HospitalCityCombo;
    private javax.swing.JComboBox<String> HospitalPinCombo;
    private javax.swing.JButton SaDocAddBtn;
    private javax.swing.JLabel SaDocCityLbl1;
    private javax.swing.JLabel SaDocCityLbl2;
    private javax.swing.JTextField SaDocCityTxt2;
    private javax.swing.JButton SaDocDeleteBtn;
    private javax.swing.JLabel SaDocHospNameLbl1;
    private javax.swing.JLabel SaDocHospNameLbl2;
    private javax.swing.JTextField SaDocHospNameTxt2;
    private javax.swing.JLabel SaDocLbl;
    private javax.swing.JLabel SaDocNameLbl1;
    private javax.swing.JLabel SaDocNameLbl2;
    private javax.swing.JTextField SaDocNameTxt2;
    private javax.swing.JPanel SaDocPnl;
    private javax.swing.JScrollPane SaDocTbl;
    private javax.swing.JButton SaDocUpdateBtn;
    private javax.swing.JButton SaHspAddBtn;
    private javax.swing.JLabel SaHspCityLbl1;
    private javax.swing.JButton SaHspDeleteBtn;
    private javax.swing.JLabel SaHspLbl;
    private javax.swing.JLabel SaHspNameLbl1;
    private javax.swing.JLabel SaHspNameLbl2;
    private javax.swing.JTextField SaHspNameTxt1;
    private javax.swing.JTextField SaHspNameTxt2;
    private javax.swing.JLabel SaHspPinLbl1;
    private javax.swing.JPanel SaHspPnl;
    private javax.swing.JScrollPane SaHspTbl;
    private javax.swing.JButton SaHspUpdateBtn;
    private javax.swing.JLabel SaSearchDocLbl;
    private javax.swing.JTextField SaSearchDocTxt;
    private javax.swing.JLabel SaSearchHspLbl;
    private javax.swing.JTextField SaSearchHspTxt;
    private javax.swing.JSplitPane SystemAdminPOVSplitHosp;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for(Hospital h : HospHistory .getHospHistory()){
            
            //System.out.println(h.getPinCode());
            
            Object [] row = new Object[3];
            row[0] = h;
            row[1] = h.getPinCode();
            row[2] = h.getCity();
            
            
            
            
            model.addRow(row);
    }
}
    
    private void populateTableNew() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        for(DoctorNew d : DocNewHistory .getDocNewHistory()){
            
            //System.out.println(h.getPinCode());
            
            Object [] row = new Object[3];
            row[0] = d;
            row[1] = d.getHospitalName();
            row[2] = d.getCity();
            
            
            
            
            model.addRow(row);
    }
}
}


