/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author felsparkle
 */
public class SystemAdminPOVperson extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPOVperson
     */
    public SystemAdminPOVperson() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SystemAdminPOVSplitPerson = new javax.swing.JSplitPane();
        SubmitSApnl = new javax.swing.JPanel();
        NamePeLbl1 = new javax.swing.JLabel();
        IdPeLbl1 = new javax.swing.JLabel();
        AgePeLbl1 = new javax.swing.JLabel();
        GenderPeLbl1 = new javax.swing.JLabel();
        AddressPeLbl1 = new javax.swing.JLabel();
        IsPatientPeLbl1 = new javax.swing.JLabel();
        SubmitPeBtn = new javax.swing.JButton();
        NamePeTxt1 = new javax.swing.JTextField();
        IdPeTxt1 = new javax.swing.JTextField();
        AgePeTxt1 = new javax.swing.JTextField();
        GenderPeTxt1 = new javax.swing.JTextField();
        AddressPeTxt1 = new javax.swing.JTextField();
        YesCb1 = new javax.swing.JCheckBox();
        EnterPersonDeetLbl = new javax.swing.JLabel();
        UpdateSApnl = new javax.swing.JPanel();
        NamePeLbl2 = new javax.swing.JLabel();
        NamePeTxt2 = new javax.swing.JTextField();
        IdPeLbl2 = new javax.swing.JLabel();
        IdPeTxt2 = new javax.swing.JTextField();
        AgePeLbl2 = new javax.swing.JLabel();
        AgePeTxt2 = new javax.swing.JTextField();
        GenderPeLbl2 = new javax.swing.JLabel();
        GenderPeTxt2 = new javax.swing.JTextField();
        AddressPeLbl2 = new javax.swing.JLabel();
        AddressPeTxt2 = new javax.swing.JTextField();
        IsPatientPeLbl2 = new javax.swing.JLabel();
        YesCb2 = new javax.swing.JCheckBox();
        EditPersonDeetLbl = new javax.swing.JLabel();
        SearchPeTbl = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchDeetsPe = new javax.swing.JLabel();
        SearchDeetsPeTxt = new javax.swing.JTextField();
        UpdatePeBtn = new javax.swing.JButton();
        DeletePeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitSApnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NamePeLbl1.setText("Name:");

        IdPeLbl1.setText("ID:");

        AgePeLbl1.setText("Age:");

        GenderPeLbl1.setText("Gender:");

        AddressPeLbl1.setText("Address:");

        IsPatientPeLbl1.setText("Is Person Patient?");

        SubmitPeBtn.setText("Submit");

        AgePeTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgePeTxt1ActionPerformed(evt);
            }
        });

        YesCb1.setText("Yes!");
        YesCb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCb1ActionPerformed(evt);
            }
        });

        EnterPersonDeetLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        EnterPersonDeetLbl.setText("Enter Person's Details");

        javax.swing.GroupLayout SubmitSApnlLayout = new javax.swing.GroupLayout(SubmitSApnl);
        SubmitSApnl.setLayout(SubmitSApnlLayout);
        SubmitSApnlLayout.setHorizontalGroup(
            SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubmitSApnlLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubmitSApnlLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(SubmitPeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EnterPersonDeetLbl)
                        .addGroup(SubmitSApnlLayout.createSequentialGroup()
                            .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(IsPatientPeLbl1)
                                .addComponent(AddressPeLbl1)
                                .addComponent(GenderPeLbl1)
                                .addComponent(AgePeLbl1)
                                .addComponent(IdPeLbl1)
                                .addComponent(NamePeLbl1))
                            .addGap(69, 69, 69)
                            .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(YesCb1)
                                .addComponent(NamePeTxt1)
                                .addComponent(IdPeTxt1)
                                .addComponent(AgePeTxt1)
                                .addComponent(GenderPeTxt1)
                                .addComponent(AddressPeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubmitSApnlLayout.setVerticalGroup(
            SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubmitSApnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(EnterPersonDeetLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamePeLbl1)
                    .addComponent(NamePeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdPeLbl1)
                    .addComponent(IdPeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgePeLbl1)
                    .addComponent(AgePeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderPeLbl1)
                    .addComponent(GenderPeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddressPeLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddressPeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SubmitSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IsPatientPeLbl1)
                    .addComponent(YesCb1))
                .addGap(61, 61, 61)
                .addComponent(SubmitPeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        SystemAdminPOVSplitPerson.setLeftComponent(SubmitSApnl);

        NamePeLbl2.setText("Name:");

        IdPeLbl2.setText("ID:");

        AgePeLbl2.setText("Age:");

        AgePeTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgePeTxt2ActionPerformed(evt);
            }
        });

        GenderPeLbl2.setText("Gender:");

        AddressPeLbl2.setText("Address:");

        IsPatientPeLbl2.setText("Is Person Patient?");

        YesCb2.setText("Yes!");
        YesCb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCb2ActionPerformed(evt);
            }
        });

        EditPersonDeetLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        EditPersonDeetLbl.setText("Edit Person's Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Age", "Gender", "Address", "Is Patient?"
            }
        ));
        SearchPeTbl.setViewportView(jTable1);

        SearchDeetsPe.setText("Search Details:");

        UpdatePeBtn.setText("Update");

        DeletePeBtn.setText("Delete");

        javax.swing.GroupLayout UpdateSApnlLayout = new javax.swing.GroupLayout(UpdateSApnl);
        UpdateSApnl.setLayout(UpdateSApnlLayout);
        UpdateSApnlLayout.setHorizontalGroup(
            UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateSApnlLayout.createSequentialGroup()
                .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateSApnlLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(EditPersonDeetLbl))
                    .addGroup(UpdateSApnlLayout.createSequentialGroup()
                        .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateSApnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(GenderPeLbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GenderPeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddressPeLbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddressPeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UpdateSApnlLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(NamePeLbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NamePeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(IdPeLbl2)
                                .addGap(18, 18, 18)
                                .addComponent(IdPeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateSApnlLayout.createSequentialGroup()
                                .addComponent(AgePeLbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AgePeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UpdateSApnlLayout.createSequentialGroup()
                                .addComponent(IsPatientPeLbl2)
                                .addGap(18, 18, 18)
                                .addComponent(YesCb2))))
                    .addGroup(UpdateSApnlLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(SearchPeTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateSApnlLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(SearchDeetsPe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchDeetsPeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateSApnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdatePeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(DeletePeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        UpdateSApnlLayout.setVerticalGroup(
            UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateSApnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(EditPersonDeetLbl)
                .addGap(18, 18, 18)
                .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamePeLbl2)
                    .addComponent(NamePeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdPeLbl2)
                    .addComponent(IdPeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgePeLbl2)
                    .addComponent(AgePeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderPeLbl2)
                    .addComponent(GenderPeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressPeLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddressPeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IsPatientPeLbl2)
                    .addComponent(YesCb2))
                .addGap(46, 46, 46)
                .addComponent(SearchPeTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchDeetsPeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchDeetsPe))
                .addGap(52, 52, 52)
                .addGroup(UpdateSApnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeletePeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        SystemAdminPOVSplitPerson.setRightComponent(UpdateSApnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SystemAdminPOVSplitPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SystemAdminPOVSplitPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesCb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesCb1ActionPerformed

    private void AgePeTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgePeTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgePeTxt1ActionPerformed

    private void AgePeTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgePeTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgePeTxt2ActionPerformed

    private void YesCb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesCb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPOVperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPOVperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPOVperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPOVperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdminPOVperson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressPeLbl1;
    private javax.swing.JLabel AddressPeLbl2;
    private javax.swing.JTextField AddressPeTxt1;
    private javax.swing.JTextField AddressPeTxt2;
    private javax.swing.JLabel AgePeLbl1;
    private javax.swing.JLabel AgePeLbl2;
    private javax.swing.JTextField AgePeTxt1;
    private javax.swing.JTextField AgePeTxt2;
    private javax.swing.JButton DeletePeBtn;
    private javax.swing.JLabel EditPersonDeetLbl;
    private javax.swing.JLabel EnterPersonDeetLbl;
    private javax.swing.JLabel GenderPeLbl1;
    private javax.swing.JLabel GenderPeLbl2;
    private javax.swing.JTextField GenderPeTxt1;
    private javax.swing.JTextField GenderPeTxt2;
    private javax.swing.JLabel IdPeLbl1;
    private javax.swing.JLabel IdPeLbl2;
    private javax.swing.JTextField IdPeTxt1;
    private javax.swing.JTextField IdPeTxt2;
    private javax.swing.JLabel IsPatientPeLbl1;
    private javax.swing.JLabel IsPatientPeLbl2;
    private javax.swing.JLabel NamePeLbl1;
    private javax.swing.JLabel NamePeLbl2;
    private javax.swing.JTextField NamePeTxt1;
    private javax.swing.JTextField NamePeTxt2;
    private javax.swing.JLabel SearchDeetsPe;
    private javax.swing.JTextField SearchDeetsPeTxt;
    private javax.swing.JScrollPane SearchPeTbl;
    private javax.swing.JButton SubmitPeBtn;
    private javax.swing.JPanel SubmitSApnl;
    private javax.swing.JSplitPane SystemAdminPOVSplitPerson;
    private javax.swing.JButton UpdatePeBtn;
    private javax.swing.JPanel UpdateSApnl;
    private javax.swing.JCheckBox YesCb1;
    private javax.swing.JCheckBox YesCb2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
